### ISSUE TITLE
Ruby 1.9.2 incompatibility issue!

### ISSUE THREAD

**Issue by jitendra** [ahoward/bj#2]
I upgraded my project from Ruby 1.8.7/Rails 2.3.2 to Ruby 1.9.2/Rails 2.3.8

In my environment file there is line to tell Bj not to manage the runner itself with

Bj.config["production.no_tickle"] = true if defined?(Bj)

Everything worked fined with Ruby 1.8.7 but after upgrade the application server does not start and throwing following exception

=> Booting WEBrick
=> Rails 2.3.8 application starting on http://0.0.0.0:3000
/Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/attributes.rb:41:in `block (2 levels) in attributes': wrong number of arguments (1 for 0) (ArgumentError)
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/attributes.rb:43:in`instance_eval'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/attributes.rb:43:in `call'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/attributes.rb:43:in`block (2 levels) in attributes'
        from (eval):3:in `call'
        from (eval):3:in`config!'
        from (eval):4:in `config'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/bj.rb:15:in`block in module:ClassMethods'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/attributes.rb:43:in `instance_eval'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/attributes.rb:43:in`call'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/bj-1.0.1/lib/bj/attributes.rb:43:in `block (2 levels) in attributes'
        from (eval):3:in`call'
        from (eval):3:in `config!'
        from (eval):4:in`config'
        from /Users/jitendra/projects/blocks/config/environment.rb:72:in `<top (required)>'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in`require'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `block in require'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in`new_constants_in'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
        from /Users/jitendra/.rvm/gems/ruby-1.9.2-p0/gems/rails-2.3.8/lib/commands/server.rb:84:in`<top (required)>'
        from script/server:4:in `require'
        from script/server:4:in`<main>'

**Comment by prismofeverything** [comment]
Any word on this?  It is destroying my world.

**Comment by pmandha** [comment]
Any solution or a pointer on this issue please.

**Comment by pmandha** [comment]
gem vibes-bj, fixed this issue for me.

**Comment by ahoward** [comment]
i'd love a pull request!
